(()=>{const form=document.querySelector('#preorder-form'),success=document.querySelector('#success-state'),photosInput=document.querySelector('#photos'),preview=document.querySelector('#photo-preview'),submitButton=document.querySelector('#submit-button'),connectionNote=document.querySelector('#connection-note'),config=window.PREORDER_CONFIG||{};let selectedFiles=[];const connected=Boolean(config.submitEndpoint);if(connected)connectionNote.classList.add('connected');
const $=s=>document.querySelector(s);const val=s=>$(s).value.trim();
document.querySelectorAll('input[name="fulfilment"]').forEach(r=>r.addEventListener('change',()=>{const pickup=$('input[name="fulfilment"]:checked').value==='pickup';$('#pickup-fields').hidden=!pickup;$('#delivery-fields').hidden=pickup;}));
$('#upload-button').onclick=()=>photosInput.click();document.querySelectorAll('.stepper').forEach(btn=>btn.onclick=()=>{const i=$('#totalItems');i.value=Math.max(1,Math.min(999,Number(i.value||1)+Number(btn.dataset.step)))});
photosInput.onchange=()=>{const incoming=[...photosInput.files],valid=incoming.filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=5*1024*1024);selectedFiles=[...selectedFiles,...valid].slice(0,5);photosInput.value='';setError('photos',incoming.length!==valid.length?'Use JPG, PNG or WebP images up to 5 MB each.':'');renderPhotos()};
function renderPhotos(){preview.innerHTML='';selectedFiles.forEach((f,i)=>{const tile=document.createElement('div');tile.className='photo-tile';const img=document.createElement('img'),url=URL.createObjectURL(f);img.src=url;img.onload=()=>URL.revokeObjectURL(url);const b=document.createElement('button');b.type='button';b.textContent='×';b.onclick=()=>{selectedFiles.splice(i,1);renderPhotos()};tile.append(img,b);preview.append(tile)})}
function setError(id,msg){const n=document.querySelector(`[data-error-for="${id}"]`);if(n)n.textContent=msg;const input=$(`#${id}`);if(input)input.classList.toggle('invalid',Boolean(msg))}
function validate(){let ok=true;const method=$('input[name="fulfilment"]:checked').value,values={name:val('#name'),phone:val('#phone'),email:val('#email'),fulfilmentMethod:method,pickupLocation:method==='pickup'?val('#pickupLocation'):'',address:method==='delivery'?val('#address'):'',itemDescription:val('#itemDescription'),totalItems:Number($('#totalItems').value),totalKg:$('#totalKg').value,dropoffLocation:val('#dropoffLocation'),plannedDropoffDate:val('#plannedDropoffDate')};const checks=[['name',values.name?'':'Please enter your name.'],['phone',values.phone.length>=6?'':'Please enter a valid phone number.'],['totalItems',values.totalItems>=1?'':'Please enter at least 1 item.'],['dropoffLocation',values.dropoffLocation?'':'Please choose a drop-off location.'],['plannedDropoffDate',values.plannedDropoffDate?'':'Please choose a date.']];if(method==='pickup')checks.push(['pickupLocation',values.pickupLocation?'':'Please choose a pickup location.']);else checks.push(['address',values.address.length>=5?'':'Please enter the destination address.']);checks.forEach(([id,msg])=>{setError(id,msg);if(msg)ok=false});const emailOk=!values.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email);setError('email',emailOk?'':'Please enter a valid email address.');if(!emailOk)ok=false;const kgOk=!values.totalKg||Number(values.totalKg)>0;setError('totalKg',kgOk?'':'Weight must be greater than 0.');if(!kgOk)ok=false;return{ok,values}}
form.onsubmit=async e=>{e.preventDefault();const r=validate();if(!r.ok){document.querySelector('.invalid')?.focus();return}if(!connected){connectionNote.scrollIntoView({behavior:'smooth'});return}submitButton.disabled=true;submitButton.firstChild.textContent='Submitting… ';try{const body=new FormData();Object.entries(r.values).forEach(([k,v])=>body.append(k,String(v)));selectedFiles.forEach(f=>body.append('photos',f));const response=await fetch(config.submitEndpoint,{method:'POST',body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to submit your request.');$('#reference-number').textContent=data.requestNumber||'Received';form.hidden=true;success.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}catch(err){alert(err.message||'Unable to submit your request. Please try again.')}finally{submitButton.disabled=false;submitButton.firstChild.textContent='Submit request '}};
$('#new-request').onclick=()=>{form.reset();$('#totalItems').value=1;$('#pickup-fields').hidden=false;$('#delivery-fields').hidden=true;selectedFiles=[];renderPhotos();success.hidden=true;form.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}})();